version: "3.3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: jump/backend
    ports:
      - "8000:8000"
    restart: always
    networks:
      - jump-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: jump/frontend
    restart: always
    networks:
      - jump-network
    depends_on:
      - backend

networks:
  jump-network:
    driver: overlay
    attachable: true
